spring.application.name=sb-ecom

# =====================
# PostgreSQL Configuration
# =====================
spring.datasource.url=jdbc:postgresql://shopnest-db:5432/sb_ecom
spring.datasource.username=postgres
spring.datasource.password=Rucha2006!!
spring.datasource.driver-class-name=org.postgresql.Driver


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always


# =====================
# JPA / Hibernate
# =====================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =====================
# File Storage
# =====================
# Change this to a path that works on your machine
project.image=images

# =====================
# JWT
# =====================
spring.app.jwtSecret=mySecretKey123912738shfygyute356r87yi6r54wsredsgfchgvknkjnjhvhgccthvjhbjkbjhgytfrdrersas
spring.app.jwtExpirationMs=86400000
spring.ecom.app.jwtCookieName=springBootEcom

# =====================
# Razorpay
# =====================
razorpay.key.id=rzp_test_SyeVFF296EqIDj
razorpay.key.secret=T74eZ2SnavrAFz81JHpPLz2D

# =====================
# Logging (reduce noise in production ? keep DEBUG for dev)
# =====================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=INFO
logging.level.com.ecommerce.project=DEBUG


# redis

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=shopnest-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ecommerce.project.payload.kafka
